### ISSUE TITLE
Artist/track not parsed from Newpipe YouTube Music releases

### ISSUE THREAD

**Issue by imogen-u** [kawaiiDango/pano-scrobbler#150]
Hi KawaiiDango,

When trying to scrobble YouTube Music releases in the app Newpipe, I am having the same problem as in #148 where Panoscrobbler gives the error "Cannot parse title (Tap to edit)". It doesn't pick up the actual artist name from the notification. The artist name is in the notification and Simplescrobbler parses the artist - title correctly. Strangely Panoscrobbler can parse some videos in Newpipe correctly (music videos, not actual YouTube music releases), as long as the format of the video name is Artist - Title.

I was hoping it might be possible for you fix this as you did in issue #148 ?

Thank you for the incredibly useful app!

edit: Added a screenshot showing Newpipe media notification and Panonscrobbler notification.

![Screenshot_2021-07-19-15-32-27-970_org schabi newpipe](https://user-images.githubusercontent.com/83655980/126177667-93f61bb1-7d9d-40fe-9fee-d1d0f7817316.jpg)

**Comment by kawaiiDango** [comment]
There is no way to differentiate between music releases and normal videos. You wouldn't want to scrobble every video with the channel name as the artist.

**Comment by imogen-u** [comment]
Hi! Thanks for the reply! Ah, I see, that makes sense. YouTube has definitely complicated things with merging Google Music and YouTube. But is it possible to make it a toggle on/off option maybe? So it could be turned off when watching videos, but work correctly for these music releases when toggled on. If not, I'll probably have to keep both Pano and Simplescrobbler installed.

**Comment by eumunhoz** [comment]
When a title can't be parsed, Pano could try looking at the channel name to see if that brings a better match, as a fallback method. I believe Web Scrobbler does that when there is no recognizable artist name in the video title.

Also, YouTube Music has really well formatted metadata, so Pano would get it right most of the time.

**Comment by nagrizolich** [comment]
> There is no way to differentiate between music releases and normal videos. You wouldn't want to scrobble every video with the channel name as the artist.

I would. Better to scrobble than not to. Besides, it often scrobbles non-music videos anyway. I would use separate Youtube apps for music and videos then and chose to scobble just from one. By the way, musiQ and Master Scrobbler can scrobble both user-submitted and Youtube Music type videos on Youtube and ignore non-music using heuristics and validation from what looks like. But they are worse apps overall.
