### ISSUE TITLE
Scrobble full artist string, e.g. "Artist1; Artist2"

### ISSUE THREAD

**Issue by Gladuin** [kawaiiDango/pano-scrobbler#238]
I'm using poweramp to listen to music in opus format, and my artist values are in seperate fields. Poweramp displays these as `Artist1; Artist2`, but pano scrobbler seems to scrobble the track only with Artist1, and not Artist1 and Artist2.

Is there a way to disable this? If not, I'd like to request it as a feature.

**Comment by kawaiiDango** [comment]
This was implemented for https://github.com/kawaiiDango/pScrobbler/issues/4
