### ISSUE TITLE
Option to locally store successfully-submitted scrobbles/listens for X amount of time

### ISSUE THREAD

**Issue by puelp** [kawaiiDango/pano-scrobbler#377]
**Is your feature request related to a problem, or particular use cases? Please describe.**

ListenBrainz recently had a data loss incident: https://blog.metabrainz.org/2023/11/04/listenbrainz-service-incident/

I'm assuming that Pano deletes scrobble/listen data after successful submission, so for ListenBrainz users, those scrobbles/listens are now irretrievably lost.

**Describe the solution you'd like**

If Pano offered an optional toggle in Settings to allow users to '_Locally store scrobble/listen data even after they've been successfully submitted_' on the device for X days/weeks/months/year, then even in cases of server-side data loss, those scrobbles could easily be restored.

This feature would also come in handy in cases where the user accidentally deletes a scrobble/listen that they did not mean to.

**Additional info**

Because this would be an optional toggle in Settings, only users who need this functionality would enable it, and so I can't think of any downsides.

**Comment by kawaiiDango** [comment]
Not planned, as events like this are very rare. You could alternatively scrobble to more than one services, as a backup

**Comment by kawaiiDango** [comment]
#388 (scrobbling to a local csv or jsonl file) has been implemened
