### ISSUE TITLE
add support for ListenBrainz "listening_from"

### ISSUE THREAD

**Issue by UltimateRiff** [kawaiiDango/pano-scrobbler#379]
I don't know if it's documented in the ListenBrainz documentation, but when submitting listens to LB, you can include what media player was used. a random example of mine from the MusicBee media player (to show how it could be submitted)

```
{
  "track_metadata": {
    "track_name": "➡ TRACK",
    "artist_name": "MEATTOOTH",
    "release_name": "➡ TRACK",
    "additional_info": {
      "trackNumber": "1",
      "artist_mbids": [
        "cfc00661-fd70-4539-a435-a3069070db3b"
      ],
      "release_mbid": "4508e620-ad56-4682-96ed-b46dd9507aa1",
      "listening_from": "MusicBee",
      "recording_mbid": "28d424f3-7b54-4afd-a7a7-d537078aaa59",
      "release_group_mbid": "feb24b66-c09b-479c-bff3-eb5e8bd6fea0",
      "recording_msid": "ec1f5a75-bdbd-4990-89fc-3d7e1d92d739"
    },
    "mbid_mapping": {
      "recording_mbid": "28d424f3-7b54-4afd-a7a7-d537078aaa59",
      "recording_name": "➡ TRACK",
      "release_mbid": "4508e620-ad56-4682-96ed-b46dd9507aa1",
      "artists": [
        {
          "artist_mbid": "cfc00661-fd70-4539-a435-a3069070db3b",
          "artist_credit_name": "MEATTOOTH",
          "join_phrase": ""
        }
      ],
      "artist_mbids": [
        "cfc00661-fd70-4539-a435-a3069070db3b"
      ],
      "caa_id": 36314206097,
      "caa_release_mbid": "4508e620-ad56-4682-96ed-b46dd9507aa1"
    }
  },
  "listened_at": 1699427431,
  "recording_msid": "ec1f5a75-bdbd-4990-89fc-3d7e1d92d739",
  "user_name": "UltimateRiff",
  "inserted_at": 1699427432
}
```

**Comment by UltimateRiff** [comment]
I brought up the lack of documentation in the ListenBrainz forums [here](https://community.metabrainz.org/t/client-identifiers-in-listen-data/446632/11?u=ultimateriff)~

**Comment by kawaiiDango** [comment]
It is called **media_player** and it is documented here https://listenbrainz.readthedocs.io/en/latest/users/json.html?highlight=media_player

I will look into implementing this

**Comment by UltimateRiff** [comment]
yeah, I blame my late night brain for that one... lol

this further discussion might be useful too: https://community.metabrainz.org/t/updates-to-recommended-listen-data-fields-to-report-clients-and-track-sources/559431?u=ultimateriff

**Comment by kawaiiDango** [comment]
I got this email recently. I think I will not be implementing this. Adding the disclosure isn't worth it just for this little feature.

![image](https://github.com/kawaiiDango/pano-scrobbler/assets/1066519/0f6c92bb-6bf0-44a5-977b-de91afc534e2)
