### ISSUE TITLE
Pano doesn't scrobble if you pause very close to the halfway mark and then resume playback

### ISSUE THREAD

**Issue by puelp** [kawaiiDango/pano-scrobbler#383]
**Describe the bug**

If you pause a track at 10% or 30%, or 43% (of the track length) and then resume playback, then Pano works as intended: it scrobbles when the track reaches 50%.

But if you pause very close to 50% and then resume playback, then Pano never scrobbles it.

I thought that maybe it would scrobble at the very last second when it reaches the end of the song, but no, it never scrobbles it.

**Steps to Reproduce**

I have the relevant settings set to:
Scrobble delay percent: 50%
Scrobble dela minutes: 03:00

I assume those are the default, because I don't think I changed them.

**App version**

The latest, which is version 3.10, but this has been happening for a while.

**Additional info**

**Comment by kawaiiDango** [comment]
Does this happen with a specific music player or specific types of songs such as short songs?

**Comment by puelp** [comment]
It happens with Metro, which is the music player that I use. I'm not sure about other music players.

The songs that I listen to are all about 3 to 4 minutes in length.

**Comment by kawaiiDango** [comment]
Should be fixed now. Can you confirm?

**Comment by puelp** [comment]
Wow I can indeed confirm that it is fixed. Thanks!

Absolutely incredible turnaround. Can you explain for us dummies what the problem was, how you narrowed down the cause, and how you fixed it?
