### ISSUE TITLE
charts question

### ISSUE THREAD

**Issue by kiyurei** [kawaiiDango/pano-scrobbler#389]
- [1 ] My question is not listed in the FAQ at https://telegra.ph/Pano-Scrobbler-FAQ-05-30
- [ 2] I am not sure whether it is a bug? So I write here.If two albums have a same song,the charts could match wrong.Just like the pictures.I scrobble a song 160 times in 1 album,but it show the song in another album.
![Screenshot_20231202_102202](https://github.com/kawaiiDango/pano-scrobbler/assets/101028325/92a239c3-acf9-4a4b-93ef-be905dc3c634)
![Screenshot_20231202_102209](https://github.com/kawaiiDango/pano-scrobbler/assets/101028325/43bd8ca0-a663-4786-b91b-8009be19c787)

- [3]I read the FaQ,Artist pictures are sourced from Spotify because the last.fm API does not provide them. so I want to ask if it is possible to add a enhancement so that I can edit the artists or albums pictures in the pano,some artist pictures show one of the album cover of them.
- [4]My English is not good,forgive me.

**Comment by kawaiiDango** [comment]
Track charts doesn't know which album you have scrobbled from. It just shows the image of the album with the most listeners, associated with that track. This is a limitation of the lastfm API. 

There no plans to add support for custom pictures right now, as it doesn't seem to be a common use case
