### ISSUE TITLE
YouTube Music ReVanced Scrobbles Previous Song's Album

### ISSUE THREAD

**Issue by wingedalpaca** [kawaiiDango/pano-scrobbler#395]
**Describe the bug**
When scrobbling from YouTube Music ReVanced and Pano Scrobbler detects an album, it scrobbles it. When the next song(s) in the playlist does not have an album, the previous song's album is used.

**Steps to Reproduce**
Listen to a song in a playlist with a detected album, then listen to the next song in the playlist without an album.

**App version**
3.14

**Additional info**

The initial song with an album -
![Screenshot_20231214_102904_Pano Scrobbler](https://github.com/kawaiiDango/pano-scrobbler/assets/12866901/566840a0-5355-47e0-ada5-4211d16399c7)

The next song in the playlist incorrectly being assigned the same album -
![Screenshot_20231214_102923_Pano Scrobbler](https://github.com/kawaiiDango/pano-scrobbler/assets/12866901/2524b667-8938-4b71-939a-4f4c67133998)

It continues.
![Screenshot_20231214_103208_Pano Scrobbler](https://github.com/kawaiiDango/pano-scrobbler/assets/12866901/10237bff-98ca-4840-8a7e-f8a43ccad568)

A few ways to fix it that I've found - 
Editing the scrobble
Closing YouTube Music ReVanced and reopening it

**Comment by wingedalpaca** [comment]
Can confirm it happens in the base YT Music app as well. Tested just now.
![Screenshot_20231214_110556_Pano Scrobbler](https://github.com/kawaiiDango/pano-scrobbler/assets/12866901/8b8b5264-760f-4448-aacd-6f2210ee41bf)

**Comment by kawaiiDango** [comment]
#344

**Comment by wingedalpaca** [comment]
Ah I see, that's too bad. Thanks for the response.
