### ISSUE TITLE
YouTube Music (free): duplicate scrobbles on last.fm

### ISSUE THREAD

**Issue by barsnick** [kawaiiDango/pano-scrobbler#399]
When playing music with the official Google YouTube Music app (with a standard Google account, not paying for YouTube), I get duplicate and triple scrobbles to last.fm.

![image](https://github.com/kawaiiDango/pano-scrobbler/assets/7283222/0727e3d3-ea9f-4854-8847-5b7571515e01)

**Steps to Reproduce**
Select an album in YouTube Music and play it. Do not interrupt playing, do not lock the screen. Observe your last.fm.

This also happens with arbitrary single songs.

**App version**
Pano Scrobbler 3.16
YouTube Music 6.29.57
running on Samsung S20 FE, Android 13 (patch level Dec 1, 2023)

**Additional info**
I had previously thought this was due to interruptions of the app, and Pano not knowing whether it's a new notification or a continuation of a previous one. Now I'm playing without interruption - except from ads - and the same thing happens.

**Comment by kawaiiDango** [comment]
If one or more ADs play before a song on YouTube music, each AD gets counted as a Scrobble of the actual song. The metadata of the AD is the same as that of the actual song except the duration. I haven't found a way to distinguish YouTube music ADs.

**Comment by kawaiiDango** [comment]
I noticed that ADs on YouTube Music are unseekable but have a finite duration (Unlike unskippable live videos). I could use this information to detect ADs playing.

**Comment by barsnick** [comment]
> If one or more ADs play before a song on YouTube music, each AD gets counted as a Scrobble of the actual song. The metadata of the AD is the same as that of the actual song except the duration.

Thanks for the explanation. I failed to notice this obvious explanation. So stupid that the app sends such notifications.

(In my mind, I was comparing with Spotify desktop's scrobbling, which omits ads, but forgot that Spotify has its own builtin-in last.fm scrobbling.)
