### ISSUE TITLE
Old edits not being applied to Youtube. Regex rules that work in test also not being applied to you

### ISSUE THREAD

**Issue by nicoleahmed** [kawaiiDango/pano-scrobbler#400]
**Describe the bug**
Latest app version 3.16

Previous YouTube edits no longer being applied. Regex Rules also not being applied. 

I have edits which have been working fine for a while which aren't working anymore. Some of these edits should be captured by new regex rules but they are not, despite testing showing they should.

![Screenshot_20231221-041639](https://github.com/kawaiiDango/pano-scrobbler/assets/38244338/8e82dd21-a146-43d2-951f-a196ba459676)
![Screenshot_20231221-041632](https://github.com/kawaiiDango/pano-scrobbler/assets/38244338/a1677499-6fa0-47af-834b-c62cfc242d51)
![Screenshot_20231221-041844](https://github.com/kawaiiDango/pano-scrobbler/assets/38244338/9f74d157-5498-48ed-a3fc-53c6fafb59fa)
![Screenshot_20231221-042001](https://github.com/kawaiiDango/pano-scrobbler/assets/38244338/be665dd5-32f7-4dd0-9eb1-8f90561bc5d4)

**Comment by kawaiiDango** [comment]
Edits are now applied to the metadata only before parsing the YouTube title, which has the channel name as the artist name and the full video title as the track name.

This will be fixed in the next update by running the edits once again to the metadata after parsing the title.
