### ISSUE TITLE
Scrobbling podcasts with chapters (Podcast Addict)

### ISSUE THREAD

**Issue by jonpsp** [kawaiiDango/pano-scrobbler#403]
- [x] My question is not listed in the FAQ at https://telegra.ph/Pano-Scrobbler-FAQ-05-30

A number of podcasts that I listen to create a few problems problems - I am scrobbling from Podcast Addict:-
- chapters
 - I usually don't care about these so don't want them as the track title
 - "PART 1" and "Outro" for example are popular chapter titles
- The podcast name is scrobbled as the album, when I want it as the artist
- The episode name is scrobbled as the artist

I have attached some screenshots as examples.  Are there magic regular expressions that would fix these?

Jon

![Screenshot_20240101-203505_Trebuchet-edit-20240101203523](https://github.com/kawaiiDango/pano-scrobbler/assets/20799382/96ff1b8c-d04c-4cf1-86dc-c08bc68a5dfa)
![Screenshot_20240101-203355_Trebuchet-edit-20240101203414](https://github.com/kawaiiDango/pano-scrobbler/assets/20799382/c0b25faf-0140-448f-8eb1-c843f5b55986)
![Screenshot_20240101-203443_Trebuchet](https://github.com/kawaiiDango/pano-scrobbler/assets/20799382/18bb8c20-7b57-4f48-aa77-80c9403ebed7)

**Comment by kawaiiDango** [comment]
So you want the current artist as the track, the current album as the artist and the album to be blank?

**Comment by jonpsp** [comment]
Yes, that is what I am looking for.

**Comment by kawaiiDango** [comment]
You can use an _extract_ rule in regex edit for that.

e.g. you would put the artist regex as (?<track>.*) and the album regex as (?<artist>.*)

**Comment by damienjryan** [comment]
For the extract rule, I've been struggling trying to make one that only kicks in iff a certain type of podcast plays.

e.g. if Album == <podcast with chapters>
           set Track to (regex to extract album without text in brackets)
           set Artist to (regex to extract album text within brackets)
           set Album to (regex to extract album without text in brackets)

**Comment by kawaiiDango** [comment]
Does "iff a certain type of podcast plays" mean any podcast where the artist is in the format of $podcastepisode \($podcastartist\)?

You could use:
artist = `(?<track>.+) (?<artist>.+)`
album = `(?<album>.*)`
