### ISSUE TITLE
Ability to Disable Friends Tab

### ISSUE THREAD

**Issue by kunalagra** [kawaiiDango/pano-scrobbler#405]
**Is your feature request related to a problem, or particular use cases? Please describe.**

I mostly use Last.fm as a way to track my Music habits and don't follow anyone. The tab is rather useless for me as it's always empty.

**Describe the solution you'd like**
Ability for users to disable the Friends tab (maybe locked behind Premium Subscription)

**Additional info**

**Comment by kawaiiDango** [comment]
This will not be implemented as this requires a lot of code changes to the current implementation but it's not a popular use case.
