### ISSUE TITLE
Artist shown twice in track and in artist 

### ISSUE THREAD

**Issue by nicoleahmed** [kawaiiDango/pano-scrobbler#409]
**Describe the bug**
Either since the latest update or since I upgraded to pro my tracks from certain apps now include the artist e.g.
Track: artistname - songtitle 
Artist: artistname 

This has affected hundreds of my scrobbles. 
I've removed all pattern edits which didn't help. 
Then I uninstalled and deleted data and this didn't help either. 
This affects a revanced version of YouTube 

**Steps to Reproduce**
Listen to music on YouTube revanced 
View scrobbled tracks with double artist data 

**App version**
Latest 18th December update 

**Additional info**
![Screenshot_20240130-091624](https://github.com/kawaiiDango/pano-scrobbler/assets/38244338/41e1fd34-51c8-4dd6-b177-492bb8ae4dcc)
![Screenshot_20240130-090440](https://github.com/kawaiiDango/pano-scrobbler/assets/38244338/c20409f4-7ada-4dc5-bb73-bb06c8b2c350)
![Screenshot_20240130-085059](https://github.com/kawaiiDango/pano-scrobbler/assets/38244338/f8798b26-a530-4b7c-8168-aeb5b0f42311)
![Screenshot_20240130-090141](https://github.com/kawaiiDango/pano-scrobbler/assets/38244338/99b3cf86-e41f-4103-a224-26728606ec84)
![Screenshot_20240114-160853](https://github.com/kawaiiDango/pano-scrobbler/assets/38244338/ca87975d-2530-4a70-bae6-60d4fe7da816)
![Screenshot_20240114-160912](https://github.com/kawaiiDango/pano-scrobbler/assets/38244338/0dbda035-9ec3-415c-926a-209708ab9eca)
![Screenshot_20240130-090440](https://github.com/kawaiiDango/pano-scrobbler/assets/38244338/064b0739-c18d-4e0e-8a75-51c1b9017fb8)
![Screenshot_20240130-085059](https://github.com/kawaiiDango/pano-scrobbler/assets/38244338/bb12a68e-0978-4d4e-bc31-3a31a4bba50a)
![Screenshot_20240130-090141](https://github.com/kawaiiDango/pano-scrobbler/assets/38244338/c346b7f2-21cd-4ac5-b084-5f8ba48c0133)
![Screenshot_20240114-160912](https://github.com/kawaiiDango/pano-scrobbler/assets/38244338/d177cc9d-0f5e-4af3-b812-db524e9f4d5e)
![Screenshot_20240114-160853](https://github.com/kawaiiDango/pano-scrobbler/assets/38244338/b70bf2e4-849e-456a-8566-d3e8c81b5a23)

**Comment by nicoleahmed** [comment]
This is the package name

app:YouTube
package:app.rvx.android.youtube

Launcher:com.google.android.youtube.app.honeycomb.Shell$HomeActivity

**Comment by kawaiiDango** [comment]
Pano never had that package name hard-coded to see it as a YouTube app to apply YouTube title parsing. This should be fixed in 3.17
