### ISSUE TITLE
Can't scrobble Youtube Music on Chromecast with Google TV

### ISSUE THREAD

**Issue by skypeias** [kawaiiDango/pano-scrobbler#412]
**Describe the bug**

Everytime I stream music from YouTube Music app on Chromecast, it won't scrobble the song that is currently playing.

**Steps to Reproduce**
Play any song on Youtube app for Chromecast/Android TV

**App version**
3.17

**Additional info**

**Comment by kawaiiDango** [comment]
It looks like Google changed something on the YouTube TV app. Other apps can no longer see what is playing on it.

**Comment by skypeias** [comment]
I guess I'll stick to casting from my phone as a workaround until it gets fixed

**Comment by skypeias** [comment]
well that sucks, i really enjoyed having my playlists on loop on the tv app while pano scrobbler would scrobble each track
