### ISSUE TITLE
Not scrobbling anything since Feb 20 update

### ISSUE THREAD

**Issue by julianb0** [kawaiiDango/pano-scrobbler#416]
Hello :)

Pano Scrobbler is an incredible app which I've been using for over a year and never had an issue until the last update

The issue I'm encountering now is simple: It doesn't seem detect either Spotify or Bandcamp playback (only 2 apps I try to scrobble from)
I don't get a "Scrobbling now" notification, nothing shows up in the scrobble history, and nothing is scrobbled

I encounter this issue on my phone, a Samsung Galaxy A8

I have checked the following things:
- Battery optimization off (it doesn't work while the app is open anyway)
- Access to notifications granted
- Doesn't work with more than 1 app (Spotify and Bandcamp, so not a Spotify issue specifically)
- The Last.fm Official App successfully scrobbles both sources (not a last.fm issue either)
- It still works on another device I use (a tablet Samsung Galaxy Tab A8)
- I tried clearing cache+data and reconnecting
- I tried uninstalling+reinstalling and reconnecting
- I tried restarting my phone

On both devices the app was updated on Feb 20th 2024

I'm not sure what other information I can give you, but tell me if there's more

**Comment by kawaiiDango** [comment]
What Android version are you using?

**Comment by pabulous** [comment]
9. It's the last that my phone will update to. I realise it's quite old!

**Comment by kawaiiDango** [comment]
v3.18 broke scrobbling on Android 10 and below. This will be fixed in the next update.

**Comment by julianb0** [comment]
Android 9 here. Thank you for the quick response.

**Comment by kawaiiDango** [comment]
Should be live on Play Store now

**Comment by pabulous** [comment]
Amazingly fast fix, thanks!
