### ISSUE TITLE
'Back' gesture causes app to crash on Realme UI 5.0

### ISSUE THREAD

**Issue by limbocadet** [kawaiiDango/pano-scrobbler#421]
**Describe the bug**
Any swipe back gesture in app will cause it to crash. (Wouldn't crash with the top left back button or buttons navigation, only gesture navigation)

**Steps to Reproduce**

**App version**
3.15 and higher

**Additional info**
system is Realme UI 5.0 (Android 14)
didn't have this problem before updating to Android 14

**Comment by kawaiiDango** [comment]
Please send a bug report from the app shortly after this happens so that it includes the logs

**Comment by limbocadet** [comment]
Pano Scrobbler v3.20 - 2024, Feb 22
Android 14
Device: realme RMX3687 / RE5854
Background RAM usage: 14M
Last exit reason: ApplicationExitInfo(timestamp=2024/3/2 07:32 pid=3363 realUid=10597 packageUid=10597 definingUid=10597 user=0 process=com.arn.scrobble:bgScrobbler reason=16 (PACKAGE UPDATED) subreason=0 (UNKNOWN) status=0 importance=125 pss=19MB rss=93MB description=stop com.arn.scrobble due to installPackageLI state=empty trace=null
[log.txt](https://github.com/kawaiiDango/pano-scrobbler/files/14466940/log.txt)

**Comment by kawaiiDango** [comment]
Please check if v3.24 fixes it

**Comment by limbocadet** [comment]
Yes it's fixed! thank you so much
