### ISSUE TITLE
Artist's top albums are ordered oddly

### ISSUE THREAD

**Issue by sorusari343** [kawaiiDango/pano-scrobbler#424]
**Describe the bug**
Artist's top albums are not the top albums.

**Steps to Reproduce**
For example, Joji's top 3 albums are "[PUSH](https://www.last.fm/music/Joji/Push)", "[SLOW DANCING IN THE DARK (Acoustic Remix) - Single](https://www.last.fm/music/Joji/SLOW+DANCING+IN+THE+DARK+(Acoustic+Remix)+-+Single)", and "[Isaiah43](https://www.last.fm/music/Joji/Isaiah43)".

**App version**
v3.20

**Additional info**

**Comment by kawaiiDango** [comment]
They are shown in order based on the number of _listeners_ and not _scrobbles_, which is not shown on the UI.

**Comment by sorusari343** [comment]
In what way would an album with a peak of 5 listeners (as opposed to [~15,000](https://www.last.fm/music/Joji/Nectar)) over the last 6 months be number 1, though?

**Comment by kawaiiDango** [comment]
Ok, this is a weird lastfm API bug I have come across. 

https://ws.audioscrobbler.com/2.0/?method=artist.getTopAlbums&artist=Joji&limit=100&api_key=key&format=json gives the wrong order but limit=99 gives the correct order. limit=101 also seems to give the correct order. The app uses 100. I'll change that number in the next update.
