### ISSUE TITLE
Voice & video messages from telegram are scrobbling

### ISSUE THREAD

**Issue by yeslyko** [kawaiiDango/pano-scrobbler#429]
**Describe the bug**
Recently [(since 14th March according to last.fm daily statistics)](https://files.catbox.moe/q67jyk.png), Telegram started displaying voice and video messages as a multimedia, which leads to Pano Scrobbler activation.

**Steps to Reproduce**
Add Telegram in Pano Scrobbler through "Scrobble from" section in app's settings. Open telegram and start some voice or video message.

**App version**
v 3.20 - 2024, Feb 22

**Additional info**

**Comment by kawaiiDango** [comment]
If the artist name is always "voice message", you can block that tag in settings > blocked metadata
