### ISSUE TITLE
Deleting a track tag doubles up all tags in the tag box

### ISSUE THREAD

**Issue by Nixinova** [kawaiiDango/pano-scrobbler#434]
**Describe the bug**

When you delete a track tag of a song, all of the tags will be added to the tag list again, resulting in everything being doubled up.

**Steps to Reproduce**

1. Tap a scrobbled song that you have previously added a tag to.
2. Remove a tag by pressing X
3. Note how all the tags are now doubled up

**App version**
v3.24 - 21/03/24

**Additional info**

**Comment by Nixinova** [comment]
Also happens when you switch apps and switch back to pano

**Comment by kawaiiDango** [comment]
Should be fixed now
