### ISSUE TITLE
Album is null for love event

### ISSUE THREAD

**Issue by regorxxx** [kawaiiDango/pano-scrobbler#436]
**Describe the bug**
This is a jsonl line for a loved track:
`{"timeHuman":"March 21, 2024, 19:43 GMT+01:00","timeMs":1711046601368,"artist":"Flume","track":"On top","album":null,"albumArtist":null,"durationMs":null,"event":"love"}
`
The same track as a scrobble:
`{"timeHuman":"March 21, 2024, 19:39 GMT+01:00","timeMs":1711046348759,"artist":"Flume","track":"On top","album":"Flume","albumArtist":"","durationMs":232150,"event":"scrobble"}`

As far as I understand, both should have the same artist, album, track data. In particular, for ListenBrainz, since loved tracks are associated to a MBID, the album is somewhat important to link the title-artist entity to an specific recording (there may be multiple versions). Using external software to perform the MBID lookup.

I understand somewhat durationMS is not saved for the love event too, since it's not required. But it may also be interesting to add it, for lookup purposes.

**Steps to Reproduce**
 
Did nothing special. Clean install of last version, jsonl profile, loved a track.

**App version**
3.24

**Comment by kawaiiDango** [comment]
Should be fixed in v3.26
