### ISSUE TITLE
Option to manually scrobble tracks/records

### ISSUE THREAD

**Issue by AlexKalopsia** [kawaiiDango/pano-scrobbler#438]
I don't know if this is in the scope or the app, or directly against its design, but quite often I find myself listening to vinyls and I would like to quickly manually scrobble a full record. I know I could use the mic as an option, but that requires me paying attention every single song. 

In other words, I would like something like the openscrobbler.com functionality to be included in PanoScrobbler.

**Comment by kawaiiDango** [comment]
Manual scrobbling is outside the scope of this app. Use [Finale](https://github.com/nrubin29/finale) which already does it better.

**Comment by AlexKalopsia** [comment]
OK, thanks for letting me know. Fwiw I love Pano and I would consider looking into adding manual scrobbling support myself if that's of any interest, I think it would make the app even more complete.

Thanks again!

**Comment by McBruno712** [comment]
> Manual scrobbling is outside the scope of this app. Use [Finale](https://github.com/nrubin29/finale) which already does it better.

The search functionality makes no sense without manual scrobbling.

And the edit functionality is basically a manual scrobble, so I don't think adding a button to scrobble search results would be out of scope.

Just my 2 cents.
