### ISSUE TITLE
Widget shows the previous/wrong artist/album/track once after having searched it

### ISSUE THREAD

**Issue by ThreeDeeJay** [kawaiiDango/pano-scrobbler#439]
**Describe the bug**
When selecting multiple artists/albums/tracks in succession in the widget to pull up the info panel, it shows the correct info every time, but if I tap Search to start playing it in an external app and go back and tap a different artist/album/track, it will show the one I just played.

**Steps to Reproduce**
- In the widget, select artist/album/track A to pull up the info panel
- Tap Search to open in an external app
- Go back to the home screen
- Select artist/album/track B
- It will show the info for artist/album/track A
- If you then exit the info panel and select artist/album/track B again, it will show the correct info

**App version**
3.26

**Additional info**
I noticed a while ago so I don't think it is a regression introduced recently.

**Comment by kawaiiDango** [comment]
Fixed

**Comment by ThreeDeeJay** [comment]
Wow that was quick.
Confirmed on my end, thanks! 👍
