### ISSUE TITLE
Artists Photos, Collage and Widget enhancement

### ISSUE THREAD

**Issue by xiaojianjian-huang** [kawaiiDango/pano-scrobbler#442]
**Is your feature request related to a problem, or particular use cases? Please describe.**
1.Lots of artists did not find matching photos.
2.Collage can be more visually impactful and meaningful.
![Screenshot_2024-03-27-03-25-50-026_com arn scrobble](https://github.com/kawaiiDango/pano-scrobbler/assets/71034510/b57fcb0f-9ae3-4bd9-aec9-af469140c121)

**Describe the solution you'd like**
Great app, thanks for maintaining it! 
Here are a few suggestions:
 1. Collage can adjust the size of artist images based on the number of plays and generate posters like "my top 10 artists"; 
![Screenshot_2024-03-27-03-44-07-066_com miui gallery](https://github.com/kawaiiDango/pano-scrobbler/assets/71034510/87b96ff6-cda1-4589-a8df-5a490bcf565b)

 2. Due to language differences, many artists do not have matching photos, such as Chinese "周杰伦" being English "Jay Chou," but no image is displayed. It is suggested to use fuzzy matching based on relevance! A switch can be added to let users decide whether to enable fuzzy matching.
![Screenshot_2024-03-27-03-01-57-993_com arn scrobble](https://github.com/kawaiiDango/pano-scrobbler/assets/71034510/b2fd6c73-ddc7-47eb-be70-cda005877db2)

 3. To improve performance, stability, and aesthetics of the widget on Xiaomi phones, it is recommended to refer to the MIUI widget documentation. It can be found here: https://dev.mi.com/console/doc/detail?pId=2466

**Additional info**
Thank you again for diligently maintaining the software and reading the suggestions. I would be well appreciate that if the suggestions will be adopted.

**Comment by xiaojianjian-huang** [comment]
@kawaiiDango hello，would you kindly consider this suggestion, please?

**Comment by kawaiiDango** [comment]
An option for approximate search for artist images has now been added where it just takes the first result from Spotify search.

That collage will not be implemented as it just complicates things and there are other tools to achieve that.

The widget follows Google's guidelines and color schemes.
