### ISSUE TITLE
Wrong album cover showing

### ISSUE THREAD

**Issue by ikuya2015** [kawaiiDango/pano-scrobbler#445]
![微信图片_20240329115525](https://github.com/kawaiiDango/pano-scrobbler/assets/72790724/13fd16f3-0bba-4b3f-b514-8f8be27a6513)
In the new version the tracks often show wrong cover in the scrobbled list.

**Comment by kawaiiDango** [comment]
Check if this still happens on 3.30

**Comment by ikuya2015** [comment]
> Check if this still happens on 3.30

sad to say, yes 😥

**Comment by ikuya2015** [comment]
In 3.30, it seems that if a song hasn't been scrobbled recently, its cover will be correct; but if it's been scrobbled recently, its cover will shows up as the previous one, even if from a different album. And edits to the album can't change the cover display.
![Screenshot_2024-04-06-02-47-00-555_com arn scrobble](https://github.com/kawaiiDango/pano-scrobbler/assets/72790724/ab402c2b-6e4c-481d-93a5-e9acdd6ab110)
![Screenshot_2024-04-06-02-47-18-813_com arn scrobble](https://github.com/kawaiiDango/pano-scrobbler/assets/72790724/85e180f2-68a4-4758-8104-00999a34ac96)

**Comment by kawaiiDango** [comment]
There was a cache bug, should be fixed in v3.31
