### ISSUE TITLE
No longer works on YouTube Music, and can no longer log in to Lastfm from app

### ISSUE THREAD

**Issue by Mari9659** [kawaiiDango/pano-scrobbler#446]
**Describe the bug**
Yesterday I saw the app wasn't working on YouTube Music, so I decided to uninstall the app and then reinstall. However, when I went to  accept access so that Lastfm could y'know use the app, I got a white background saying this, The page failed to load (is your internet working?)
net::ERR_UNKNOWN_URL_SCHEME

I have no idea what this means and I have tried researching on Chrome for anything, and everything I tried just failed. I need some help to fix this, thank you.

**Steps to Reproduce**
What? Sorry this makes no sense to me

**App version**
I think it's the current version

**Additional info**
Yesterday I was trying to clear up storage on my Android phone, and I'm afraid I deleted something important. I also did disable Pano on my Lastfm to see if that did anything but nope. I tried sending a screenshot but my phone sucks

**Comment by kawaiiDango** [comment]
Check if this still happens on 3.30

**Comment by Mari9659** [comment]
> Check if this still happens on 3.30

You must mean version 3.30. Well it turns out I am on version 3.27, which I didn't know til now. It wont show that I can update the app in the play store, and I tried updating the play store but it seems up to date.

**Comment by kawaiiDango** [comment]
Google has not approved my update yet. You can get it from GitHub releases https://github.com/kawaiiDango/pano-scrobbler/releases

**Comment by Mari9659** [comment]
Well the model says SM-S32VL and the version of my android is 6.0.1. What is weird tho is that the app was working fine since 2021, but after getting rid of some stuff on my phone's storage, I am afraid I deleted something important on accident or something

**Comment by Mari9659** [comment]
Ohhhh okay, well thank you for telling me. Hopefully after the next update it will finally work

**Comment by kawaiiDango** [comment]
should be fixed in v3.31
