### ISSUE TITLE
Pano scrobble not supporting new pipe

### ISSUE THREAD

**Issue by deeplydispirit** [kawaiiDango/pano-scrobbler#447]
**Describe the bug**
Whenever I try to use the new pipe application with pano I get a couldn't parse title error. 

**Steps to Reproduce**
Using newest new pipe playing songs from soundcloud newpipe client

**App version**
Newest up-to-date version 

**Additional info**

**Comment by kawaiiDango** [comment]
fixed in v3.37

**Comment by githubtefo** [comment]
Any plans to add NewPipe as the supported Apps for search scrobbled albums/ songs?
Great work!

**Comment by kawaiiDango** [comment]
https://github.com/kawaiiDango/pano-scrobbler/issues/414
