### ISSUE TITLE
Tags are able to be added with trailing spaces

### ISSUE THREAD

**Issue by Nixinova** [kawaiiDango/pano-scrobbler#448]
**Describe the bug**
Tags are able to be added with preceeding and trailing spaces which breaks Lastfm.

**Steps to Reproduce**
1. Tap a song
2. Tap the add tags button
3. Write something like "one, two" and press Add.
You will see that the submitted tags to Lastfm are `one` and `+two` instead of `one` and `two`. This makes the tags impossible to edit on Lastfm; these erroneously spaced tags can only be removed in the app.

**App version**
v.3.27 - 2024-03-25

**Additional info**
I thought using commas would just be an easier way to add multiple tags to a track with the app instead of pressing "Add" individually but this has broken it

**Comment by kawaiiDango** [comment]
Fixed in 3.30

**Comment by Nixinova** [comment]
thanks again for the quick fix
