### ISSUE TITLE
Select multiple scrobbles

### ISSUE THREAD

**Issue by nicoleahmed** [kawaiiDango/pano-scrobbler#450]
Great work going on as always. Thanks 

I would like to be able to select multiple scrobbles particularly for deleting. I had a look through your issues and couldn't see it suggested - sorry if you've dealt with this already. 

This could be implemented either with long press for selecting multiple tracks or a check box option. 

I think there may be a limitation to how many scrobbles can be deleted at a time in last.fm so this may need some thought for timings of requests and how this can be managed in the background. Sorry I'm not familiar enough with those processes to suggest something myself. 

Not life or death, but would be nice to have

Thanks

**Comment by kawaiiDango** [comment]
Deleting many scrobbles in a short period of time WILL hit the rate limit on lastfm. I had to add an artificial delay in the current implementation to get around that. So, this will not be implemented.
