### ISSUE TITLE
loved track widget / notification bar button

### ISSUE THREAD

**Issue by magnumforce2006** [kawaiiDango/pano-scrobbler#451]
Pretty simple request that this paid user would love to see:

A simple heart widget that one can press to love the current playing track.

A button that you can throw into the notification quick tiles settings would also be very cool!

**Comment by magnumforce2006** [comment]
Actually I see in other threads something like thos can probably be achieved with an intent.

Could you explain the parameters of said intent to love a track with this app?

**Comment by kawaiiDango** [comment]
The scrobbling notification already has a heart button

**Comment by magnumforce2006** [comment]
That is one way to love the track, yes, but that is not always the quickest/easiest way to love a track depending on what's going on with the phone. 

You've mentioned in other threads that there's an "intent" within Pano Scrobbler that can be used to love tracks. This would be beneficial to understand for those of us to use something like Macrodroid to set up commands and buttons ourselves. 

Can you please explain how this is setup using Macrodroid?

**Comment by kawaiiDango** [comment]
In Macrodroid, create a rule, use the _Send intent_ action, select the target as _broadcast_ and paste the intent text in _action_.

The list of intents for pano scrobbler can be found in the intents section in the _configure_ screen.

**Comment by magnumforce2006** [comment]
Thank you! However, I am not seeing that section in the Configure Screen. The only sections I see in Configure are:

-top header (scrobble music, add quick settings tile)
-Scrobble From
-Scrobble Delay
-Personalization
-Lists
-Languages
-Notifications
-Misc.
-Import & Export
-Services
-About

Is it under one of these and I'm just missing it somehow?
