### ISSUE TITLE
Album art icon is cached by title not by album

### ISSUE THREAD

**Issue by Nixinova** [kawaiiDango/pano-scrobbler#454]
**Describe the bug**

Album art is cached by the title, which is useful for showing album art when it is scrobbled without an album, but when you listen to one track that is part of two different albums they both display the same album art icon instead of the two different arts.

**Steps to Reproduce**
1. Scrobble a song from an album. E.g.: [from album1](https://open.spotify.com/track/6gUUTek9fAM9UiEB58Oomd?si=35adIHPZTzy7ryCACRb4KA)
2. Scrobble the song from another album. E.g.: [from album2](https://open.spotify.com/track/4slbQxodrso1KcxwoiNXU9?si=uQqu2vvBTV2Abb6aUYibgg&context=spotify%3Aalbum%3A2gnr6cs8MEKscvCwZGpRJG)
3. View in pano scrobbler. The icons will be the same even though the albums are different.

**Image**

![Screenshot_20240422-163025.png](https://github.com/kawaiiDango/pano-scrobbler/assets/42429413/e9b4383d-fa7f-41bc-af7a-8f31b86c9ead)
Scrobbled a song from two albums. The album icon is the same for both but as you can see when I tap one it shows the correct art in the big art on the top of the screen.

**App version**
v3.27

**Additional info**

**Comment by kawaiiDango** [comment]
Already fixed https://github.com/kawaiiDango/pano-scrobbler/issues/445

Unfortunately Google has rejected all every update after 3.27 due to UI issues on Android TV
