### ISSUE TITLE
Jazz Music Radio (Android) - incorrect scrobbles

### ISSUE THREAD

**Issue by dariusz-wozniak** [kawaiiDango/pano-scrobbler#456]
**Describe the bug**
The [JAZZ MUSIC RADIO](https://play.google.com/store/apps/details?id=com.audioaddict.jr&hl=en&gl=US) app scrobbles in a wrong way on the Android. It scrobbles in a pattern:

- Artist: artist - title
- Title: station name

For example:

- Artist: Christian McBride Trio - I Have Dreamed
- Title: Late Night Jazz

See example: https://www.last.fm/music/Christian+McBride+Trio+-+I+Have+Dreamed

**Steps to Reproduce**

- Just play JAZZ MUSIC RADIO

**App version**

- Pano Scrobbler: 3.27
- Jazz Radio: 5.0.5.11022

**Additional info**

The app is from a Digitally Imported company; they also have an electronic equivalent app - DI.FM Radio - which scrobbles correctly.

**Comment by kawaiiDango** [comment]
Related issue https://github.com/kawaiiDango/pano-scrobbler/issues/152
