### ISSUE TITLE
Stop collecting (store) scrobbles after a while.

### ISSUE THREAD

**Issue by aklomsta** [kawaiiDango/pano-scrobbler#457]
I'm using Pano to schrobbles to Last FM  and discover that many scrobbles where missing.
When I checked Pano I see that the app stopp collecting (store) scrobbles after a while.
When I open the appen it restarts to collected and sent them to Last FM including two or three previous scrobbles, but scrobbles previous that are missing. It performs good for a while (1/2 -1 hour) and scrobbles as expected before it stops.

v. 3.27 - 2024, Mar 25

Samsung  S23 Ultra One UI 6.1 Android 14

has occurs for a while (several previous versions)

**Comment by kawaiiDango** [comment]
Read the FAQ

**Comment by aklomsta** [comment]
Thank you. I read the FAQ, but I missed a detail. I though my battery setting was correct.
