### ISSUE TITLE
The Extract Feature!

### ISSUE THREAD

**Issue by isthatwyll** [kawaiiDango/pano-scrobbler#458]
Hi!

I'm having quite a headache trying to figure out how to make use of this new extract feature. I have a private web readio that streams the metadata in the [track] tag as follows:
[artist • track • album]
Example:
Bon Jovi • Never Say Goodbye • Slippery When Wet (Deluxe)

I'd like to make it so that the fields between bullet points get extracted to the metadata field it belongs to, I tried several regex combinations but none were successful.

If someone could help me or point me to a direction, I'd be grateful!!!

**Comment by kawaiiDango** [comment]
Use this for track `(?<artist>.*) • (?<track>.*) • (?<album>.*)`

**Comment by isthatwyll** [comment]
OMG many thanks, worked like a charm!!!!
