### ISSUE TITLE
Permissions issue - apparently core  functionality depends on microphone permission

### ISSUE THREAD

**Issue by alexmitrani** [kawaiiDango/pano-scrobbler#460]
**Describe the bug**
App doesn't show notification when microphone permission not granted, gets killed by system after a few scrobbles. 

User has option to refuse microphone permission and it seemed reasonable to do so because it was not clear from description that microphone is always needed for app to work.  However, it seems that without granting this permission app does not work as intended. Please could you clarify why microphone permission is needed if I don't scrobble using microphone?  Does it always scrobble using the microphone?  If microphone is not needed for core functionality the app should be able to work without this permission.  If microphone is needed for core functionality, the user should be warned that this is the case when they don't grant that permission.  I almost stopped using the app because I didn't understand why it wasn't working and there was no explanation. 

**Steps to Reproduce**
Use app with microphone permission not granted for about half an hour, observe how notifications don't show and it gets killed by system. 

**App version**
Pano Scrobbler v3.27 - 2024, Mar 25

**Additional info**
motorola moto g24 power, Android 14

**Comment by alexmitrani** [comment]
Update: after granting the microphone permission it worked for 15 scrobbles before being killed by the system again. - a record on this phone. Now the notifications are not showing, it is not working, and I don't know how to revive it. It seems like battery optimisation got turned on again despite me having turned it off previously. I turned battery optimisation off again but it still is not working. I guess it might start working again if I restart the phone but that does not seem like a reasonable solution.

**Comment by kawaiiDango** [comment]
The microphone permission has nothing to do with scrobbling and is not needed unless you are using the "scrobble from mic" feature. This issue is misleading.

Your actual issue might be similar to #463
