### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by Robin-Sch** [kawaiiDango/pano-scrobbler#461]
**Describe the bug**
Since I installed pano scrobbler, I noticed a significant increase in battery usage.

**Steps to Reproduce**
Uninstall pano, charge to 100% and don't touch the phone for a few hours (not playing music).
Then, charge again to 100% and install pano. Then once again put your phone away and don't touch it for a few hours (and don't play music).

I noticed that with pano installed, my phone drains like 10-20% more battery than without it (going from 100 to 20-30ish vs 40ish), tested multiples times.

I have set battery usage permission to "unrestricted"

**App version**
3.35, fdroid

**Comment by kawaiiDango** [comment]
Which device do you have? You don't usually need to set battery usage to unrestricted unless your OEM has a bad rating on dontkillmyapp.com

**Comment by Robin-Sch** [comment]
I am running lineageos, same thing happens with battery being set on optimised (default one)

**Comment by kawaiiDango** [comment]
I found a timer that was ticking all the time. That will be fixed in the next update.

**Comment by kawaiiDango** [comment]
Should be fixed in v3.37

**Comment by opentypefont** [comment]
I have same issue in v3.44
I'm using Samsung Galaxy with One UI 7.0 on Android 14, and battery optimization is disabled for Pano.
Pano using too much CPU although it sent just 10K packets while YouTube sent 90K packets.
I enabled regex pattern fix. Could it be the reason of battery drain?
