### ISSUE TITLE
Pocket Casts Chapters 

### ISSUE THREAD

**Issue by oddtoddy** [kawaiiDango/pano-scrobbler#464]
- [ ] My question is not listed in the FAQ at https://telegra.ph/Pano-Scrobbler-FAQ-05-30

Now that Pocket Casts supports chapters, does anyone know if there is a way to scrobble chapters instead of the whole episodes? I'm thinking it might not be possible unless Pocket Casts changes the way they display the Now Playing notification but I'm not sure. Any ideas?

**Comment by kawaiiDango** [comment]
It is not possible as pano doesn't have access to the information about chapters

**Comment by oddtoddy** [comment]
Right on. Appreciate the reply and all of your hard work on this app!
