### ISSUE TITLE
Scrobbler doesn't detect music/scrobbles from Symfonium when using classic notification style (not Media Session)

### ISSUE THREAD

**Issue by tobyburton96** [kawaiiDango/pano-scrobbler#468]
**Describe the bug**
Hi, Android Media Session is bugged on my version of the OS, and so I have to disable it where I can. 
Using the local music player Symfonium (https://play.google.com/store/apps/details?id=app.symfonik.music.player&hl=en_GB), I can disable it in Settings > Advanced > Disable media session usage in order to use classic Android style notifications.
In this instance, Pano does not seem to detect a scrobble.

**Steps to Reproduce**
1. Install Symfonium and disable Media session (and restart app)
2. Enable app to be scrobbled in Pano settings
3. Play music through Symfonium
4. No response from Pano

**App version**
v 3.27
Android version 11

**Additional info**

Symfonium has a time limited trial to test. When it runs out, it can be rearmed for 24 hours by reinstalling. 
I am happy to test anything if this is inconvenient.
Simple last.fm scrobbler also does not pick up anything in this same situation - meaning I went to the Symfonium dev first, but he said there is no way for him to investigate this and to ask here.

A picture of the notification in question:
![symfonium notification](https://github.com/kawaiiDango/pano-scrobbler/assets/171647890/993a0d15-1fd9-458c-be06-7bfc172041c9)

Thank you very much. 
Toby

**Comment by kawaiiDango** [comment]
Pano works by listening to media session metadata and events from other apps. It can't scrobble if there is no media session in the first place. Other modern scrobblers also work this way. So, this is expected behaviour.

**Comment by tobyburton96** [comment]
Ah, I see. I traditionally used simple scrobbler, which could read text from notifications that didn't use the new Android style media notifications (from the app Blackplayer). I was under the impression this situation was analogous on both scrobbler and player end.

Looks like I may have to upgrade to Android 12 to fix the root bug. I'm scared.

Thanks for the reply
