### ISSUE TITLE
App only scrobbles once when a track is on repeat (TIDAL)

### ISSUE THREAD

**Issue by soogyuist** [kawaiiDango/pano-scrobbler#469]
- [ ] My question is not listed in the FAQ at https://telegra.ph/Pano-Scrobbler-FAQ-05-30

When I put a track on loop on TIDAL, Pano only scrobbles it once and never does it again. I am using a Samsung Z Flip 3 and I've also set the battery optimisation for the app to unrestricted (if that matters, of course). Is there something I can do to solve this issue?

**Comment by kawaiiDango** [comment]
Tidal does not send any media session event when a track starts repeating, so it is not possible to know if it was repeated. This is a Tidal bug.
