### ISSUE TITLE
Scrobbling to webhook

### ISSUE THREAD

**Issue by tepiloxtl** [kawaiiDango/pano-scrobbler#470]
**Is your feature request related to a problem, or particular use cases? Please describe.**
I'd like to be able to submit listens to a webhook, which would enable for rolling custom additional functionality as a middleman service

**Describe the solution you'd like**
Web scrobbler have a webhook API, it does look good and fairly complete, although I'm aware some of the information provided might not be possible to capture on Android. If this format is to be picked up, additionally, a field in the root of request containing some identifier of application sending scrobble to webhook (so something like "application": "Pano Scrobbler")

**Additional info**
https://github.com/web-scrobbler/web-scrobbler/wiki/Webhook-API

**Comment by kawaiiDango** [comment]
What is the use case? Any of the self hosted scrobbling options in the app should be good in most cases.

**Comment by dotargz** [comment]
I believe that implementing this functionality would allow for _new_ self hosted scrobbling options to be created and used without explicit support and implementation. For example, a user may want to create their own self-made, and self-hosted scrobbler.

**Comment by mattn** [comment]
I use a social networking service/protocol called Nostr. The Nostr protocol has a mechanism for displaying "now playing." I use [nostr-status-lastfm](https://github.com/mattn/nostr-status-lastfm), which I am developing, to sync this status with the latest track from lsat.fm. However, this software requires a server environment that can run cron job, but many users do not have it. Therefore, I think that if Pano Scrobbler can call a webhook, many users will be able to update this status inexpensively. I believe that it can be implemented for free using cloudflare workers, for example.

**Comment by kawaiiDango** [comment]
Pano Scrobbler supports scrobbling to self hosted listenbrainz compatible servers, gnufm (compatible with lastfm), pleroma and maloja. You can think of them as webhooks for well established scrobbling protocols.

For example, you can create a proxy that accepts scrobbles in the listenbrainz api format and forwards them to nostr. You would only need to implement the auth and the scrobble submission endpoints for listenbrainz and leave out the rest. This can then be hosted on cloudflare workers or similar services.

I don't want to invent and maintain yet another scrobbling format exclusive to Pano Scrobbler, that no one will use.

**Comment by mattn** [comment]
Thank you for your reply. I see your point. Do you know of any small or simple server implementation OSS that can be used from Pano Scrobble?

**Comment by kawaiiDango** [comment]
You can take a look at https://github.com/krateng/maloja which also implements listenbrainz and gnufm compatible auth and scrobbling endpoints, in addition to its own.

**Comment by dotargz** [comment]
> Pano Scrobbler supports scrobbling to self hosted listenbrainz compatible servers, gnufm (compatible with lastfm), pleroma and maloja. You can think of them as webhooks for well established scrobbling protocols.
> 
> For example, you can create a proxy that accepts scrobbles in the listenbrainz api format and forwards them to nostr. You would only need to implement the auth and the scrobble submission endpoints for listenbrainz and leave out the rest. This can then be hosted on cloudflare workers or similar services.
> 
> I don't want to invent and maintain yet another scrobbling format exclusive to Pano Scrobbler, that no one will use.

If you dont want to invent a new format, you could use the same format for webhooks that Web Scrobbler uses! This would allow both of the most popular scrobblers to have the same custom format. Of course, up to you!

**Comment by mattn** [comment]
@kawaiiDango one more question please, if I implement a pseudo scrobble server, which last.fm APIs should be implemented to interact with pano-scrobble?

**Comment by kawaiiDango** [comment]
It is not possible to implement something compatible with web scrobbler's webhook format. A lot of the data it needs, are not kept track of by pano, or are simply not available with the Android APIs.

For a self hosted last.fm compatible server (gnufm), it needs auth.getMobileSession, track.updateNowPlaying and track.scrobble.
