### ISSUE TITLE
[Bug] "Now Scrobbling" Notifications Not Visible When Playing on Spotify

### ISSUE THREAD

**Issue by KrrixhhDotExe** [kawaiiDango/pano-scrobbler#471]
**Describe the bug**
When playing music on Spotify, the "Now Scrobbling" notification from Pano Scrobbler is no longer visible. This issue started occurring recently. 

Despite the missing notification, scrobbling still functions correctly. 

Notification permissions for Pano Scrobbler have been checked and are configured properly.

**Steps to Reproduce**
1. Open Spotify and start playing a track.
2. Observe that the "Now Scrobbling" notification from Pano Scrobbler does not appear.

Screenshots: 
![1718518066864_temp_llcrop.jpg](https://github.com/kawaiiDango/pano-scrobbler/assets/96946509/32cef577-3011-48bc-b3e0-797dff0c097e)

![1718518099189_temp_llcrop.jpg](https://github.com/kawaiiDango/pano-scrobbler/assets/96946509/b5d81cec-1a30-47af-8708-bb1ddc16207d)

**App version**
![1718518432017_temp_llcrop.jpg](https://github.com/kawaiiDango/pano-scrobbler/assets/96946509/17df4f63-9007-40fd-95af-f0b78116b87a)

OS: Android 11
Device: Vivo Y15

**Additional info**
This issue was not present before and started occurring recently. Notification permissions for Pano Scrobbler are set correctly.
Screenshots:

![1718517971127_temp_llcrop.jpg](https://github.com/kawaiiDango/pano-scrobbler/assets/96946509/f876667e-1e94-4d40-a6eb-1599ab04c800)

![1718518009755_temp_llcrop.jpg](https://github.com/kawaiiDango/pano-scrobbler/assets/96946509/58983508-6a56-4c1b-906e-8565f1a6c495)

**Comment by kawaiiDango** [comment]
Some Android skins don't show silent notifications by default. Check if that is the case. There might have been an os update that changed that setting.

**Comment by KrrixhhDotExe** [comment]
It started working on it's own a few days later. Never knew why it happened but it's working well since then.
