### ISSUE TITLE
Friends Tab throws a 400 error

### ISSUE THREAD

**Issue by letruxux** [kawaiiDango/pano-scrobbler#472]
**Describe the bug**
A "(400)" popup shoes up when opening the friends Tab, and it's blank

**Steps to Reproduce**
open the friends Tab

**App version**
3.27

**Additional info**
I'm using lastfm as a provider, scrobbling soundcloud

**Comment by kawaiiDango** [comment]
This must be a temporary error as I don't have it. Anyways update the app to 3.35 from GitHub releases.

**Comment by letruxux** [comment]
I updated and now the tab works. check the _new_ issue if you haven't yet
