### ISSUE TITLE
Enable "Scrobble parties"

### ISSUE THREAD

**Issue by Chuhtra** [kawaiiDango/pano-scrobbler#473]
I would like to be able to use another user's scrobling feed, to scrobble in my own feed. For occasions that we listen to music together, like gatherings, parties etc.

**Describe the solution you'd like**
- I would like to be able to name a user (e.g. from last.fm) and scrobble data from their music feed.
- This can include scrobbling 
    - until unset (toggle button)
    - "from now on until X minutes in the future"
    - for a previous set of time (start, end date/hour and/or duration) - for historical data.

**Additional info**

Current solution that only partly allows this: https://scrobblewith.com/

Thanks for all your work!

**Comment by kawaiiDango** [comment]
Use [Finale](https://github.com/nrubin29/finale) which already does it.
