### ISSUE TITLE
pro version in huawei

### ISSUE THREAD

**Issue by TaprisSugarbell** [kawaiiDango/pano-scrobbler#477]
**Is your feature request related to a problem, or particular use cases? Please describe.**
Pano Scrobbler is not available on Huawei's AppGallery and for the most part the app has no problems, there is just no way to donate to get the pro version.

**Describe the solution you'd like**
A way to be able to get the pro version in huawei, a key with a limited number of uses and that only works on one device to avoid possible misuse of the key to take advantage of the same.

**Comment by kawaiiDango** [comment]
Continue in #229
