### ISSUE TITLE
Multiple artists from Youtube Music that are written with comma or with &

### ISSUE THREAD

**Issue by ivaikosan** [kawaiiDango/pano-scrobbler#479]
Unlike Spotify, when scrobbling from youtube music some tracks has metadata with two or more artists in naming and pano doesn`t clear this thing, so i suggest an option to automatically scrobble the name of the first artist and ignore everything that comes after , or & or and (in other languages youtube music uses form of the word 'and')

**Comment by kawaiiDango** [comment]
There is no reliable way to do this, as a single artist can have commas and &s in their names. See https://github.com/kawaiiDango/pano-scrobbler/issues/358#issuecomment-1670597434 and #177

**Comment by ivaikosan** [comment]
Yeah, had this thought too, thanks for answering!
