### ISSUE TITLE
ListenBrainz month statistics show data for the wrong month.

### ISSUE THREAD

**Issue by egecelikci** [kawaiiDango/pano-scrobbler#481]
**Describe the bug**
The August tab shows data from July and the July tab shows data from June

**Steps to Reproduce**
use ListenBrainz as a service then check data of the months (couldn't understand if other tabs are also represents the wrong data though, probably not.)

**App version**
`3.36 - 2024, Aug 01`

**Additional info**
in this version app started showing data quickly and directly from ListenBrainz, thanks for that

**Comment by kawaiiDango** [comment]
Aug and July correspond to "This month" and "Last month" on the listenbrainz website. The website is still showing data from July in "This month".
