### ISSUE TITLE
"Support this app" button does not work

### ISSUE THREAD

**Issue by inzsome** [kawaiiDango/pano-scrobbler#483]
**Describe the bug**
The "support this app" button does not respond to taps. Thus, you currently can't purchase the premium version of this app. 

**Steps to Reproduce**
1. Open app
2. Log into last.fm
3. Tap on user icon
4. Tap on "Support this app" 
5. Tap on "Support this app" button (it doesn't work, doesn't open a new window, etc.)

**App version**
3.3.7, 2024 Aug 7

**Additional info**
Here's a screen recording

https://github.com/user-attachments/assets/a8974d96-8531-45e8-ad7f-105fd573d9cc

In the meantime, is there any way to purchase the app via a link to the play store?

**Comment by kawaiiDango** [comment]
This can usually be fixed by updating Google Play Services. If it is already up to date, please send a bug report from the app shortly after replicating this bug.

**Comment by inzsome** [comment]
Updating wasn't necessary, it worked, all of a sudden. Thanks.
