### ISSUE TITLE
Extract mode appears not to work for audible.

### ISSUE THREAD

**Issue by djryan** [kawaiiDango/pano-scrobbler#489]
**Describe the bug**
I’ve added an extract rule for Audible, which scrobbles the Chapter as artist, but the album as both track and album.

![Screenshot_20240820-172459_Original](https://github.com/user-attachments/assets/175eaa90-464f-4fd5-9214-c5cff9d8432b)

Using the build in regex tester, this rule gets fired, but when I play in Audible, it doesn’t.

**Steps to Reproduce**

**App version**
3.38

**Android version**
15

**Additional info**

**Comment by kawaiiDango** [comment]
I thought about this, a possible cause could be that the purchase info did not get updated in the background scrobbling process. Force closing and reopening the app should fix that.

**Comment by djryan** [comment]
It seems to be happening despite phone reboots and on different, already purchased, books.  Is the suggestion to download, then force close audible and start again?

**Comment by kawaiiDango** [comment]
I meant force closing pano scrobbler

**Comment by djryan** [comment]
No joy.  Tried force closing, force closing through app settings, both while audible playing and audible not playing.

**Comment by kawaiiDango** [comment]
Will try to fix it in the next update

**Comment by kawaiiDango** [comment]
Does it work for other apps? If not, share your settings export file so that I can replicate this on my device.

**Comment by djryan** [comment]
You're right; it's not just Audible. Extract seems to work in test mode though. Attached settings. 
[pano_scrobbler_export_2024_8_31_14_31.json](https://github.com/user-attachments/files/16824984/pano_scrobbler_export_2024_8_31_14_31.json)

**Comment by kawaiiDango** [comment]
Is this bug still present on your end?

**Comment by djryan** [comment]
Looks like it’s working again now.
