### ISSUE TITLE
Pano scrobbler draining battery

### ISSUE THREAD

**Issue by Yohe-Am** [kawaiiDango/pano-scrobbler#496]
**Describe the bug**

Recently, I've noticed the battery life on my phone has dwindled drastically and the battery reporter repeatedly fingers Pano as the culprit.

**Steps to Reproduce**

Leave app in background after disabling OS battery protections measures for app.

**App version**

3.39

**Android version**

13

**Additional info**

ZTE's MyOs skin that has minimal, almost stock like android setup.

**Comment by kawaiiDango** [comment]
It could be a data migration issue that I didn't handle. Take a backup by exporting your settings and then clear data or reinstall the app.

**Comment by etymotic** [comment]
> It could be a data migration issue that I didn't handle. Take a backup by exporting your settings and then clear data or reinstall the app.

This worked for me. Battery current decreased by more than 1000mA after resetting things. Pretty big.

**Comment by Yohe-Am** [comment]
Okay, it's been a few weeks and the suggestion indeed seems to have worked. Thanks!
