### ISSUE TITLE
Recent scrobbles not loading, everything else works

### ISSUE THREAD

**Issue by dgudim** [kawaiiDango/pano-scrobbler#503]
**Describe the bug**
On the main app screen, recent scrobbles list is not loading

**Steps to Reproduce**
Open the app, try to load recent scrobbles

**App version**
3.39

**Android version**
13

**Additional info**
Liked and custom time ranges work

https://github.com/user-attachments/assets/cf4ff86a-d8a6-42dd-a241-d12754656aad

**Comment by kawaiiDango** [comment]
Clear cache and then force stop the app

**Comment by dgudim** [comment]
Ok, this worked. Thanks!
