### ISSUE TITLE
"Nintendo Music" not scrobbling

### ISSUE THREAD

**Issue by BlueInterlude** [kawaiiDango/pano-scrobbler#508]
**Describe the bug**

The new "Nintendo Music" application, https://www.nintendo.com/us/switch/online/nintendo-switch-online/nintendo-music/, does not seem to be scrobbling properly. Tracks do not appear in the application when the song is playing nor when the song is complete. 

**Steps to Reproduce**

1. Download the new "Nintendo Music" application.
2. Add the application to Pano Scrobbler's whitelist if necessary.
3. Play a song on the "Nintendo Music" application and see if Pano Scrobbler picks it up.

**App version**

v 3.39 - 2024, Aug 26

**Android version**

14

**Additional info**

This application just came out today (October 30th) so I apologize for the hastiness of this issue. I've been using Pano Scrobbler for years now and have loved using it! I am in no hurry on adding support for "Nintendo Music", but wanted to bring this up so support could be added down the road (or maybe it's just simple user error).

**Comment by RuiNtD** [comment]
I just came here to report this. I don't think this is user error. I tried force stopping and reopening Pano and Nintendo Music with no luck. I see the same issue with the official Last.fm app.

**Comment by kawaiiDango** [comment]
I checked the bug report logs which one of you probably mailed. The app only puts the album name and the title in the metadata. There is no artist. The scrobbling services do not accept scrobbles without an artist.

**Comment by Maddieman** [comment]
Hi Jon from last.fm here.  In lieu of Nintendo adding composer info (hopefully they will in a later update), what do you think about attributing songs from the app to Nintendo Co., Ltd. (https://www.last.fm/music/Nintendo%20Co.,%20Ltd.)? You can do Nintendo, but afaik it's technically a shared artist page with some russian rapper and might be problematic.  Either way it would be useful if both your app and ours scrobble to the same artist page, so people's scrobbles don't get split up -- at least until Nintendo attribute the tracks to their composers (which they may or may not do).

**Comment by RuiNtD** [comment]
Here is a screenshot of the Media Controller Tester while playing a song [extended to](https://support.m.nintendo.com/hc/en-us/articles/10524850498959-What-is-Extend-to-and-how-does-it-work) 15 minutes:
https://github.com/user-attachments/assets/9135b367-6473-4308-93c4-0b203a2b9d7c

The app itself doesn't even provide artist information, which is one of the big complaints I've seen online about the app. Going to "Track information" for **any song** only shows something like:
> Gusty Garden Galaxy
> Super Mario Galaxy
> © Nintendo
