### ISSUE TITLE
Does not scrobble YouTube mix songs

### ISSUE THREAD

**Issue by GetPsyched6** [kawaiiDango/pano-scrobbler#513]
**Describe the bug**
looks like it was a temporary bug. Seems to be working again.
~When listening to a YouTube mix, when the next track starts, Pano doesn't catch the new song, and the notification still shows the previous song's name. Upon tapping on the notification, Pano starts to recognize that a different song is playing~

**Steps to Reproduce**
1. ~Start any mix on the YouTube app~
2. ~Let the next song play automatically after the first song ends~
3. ~Pano does not scrobble this song and all subsequent ones~

**App version**
v 3.42

**Android version**
Android 14, One UI 6.1

**Additional info**
Thanks for this great app! It's near perfect

**Comment by kawaiiDango** [comment]
It could be the system killing the app when in the background. Tapping the notification essentially starts the processes again (if they weren't running). 

See dontkillmyapp.com and #463

**Comment by GetPsyched6** [comment]
Switching the battery settings from normal to unrestricted appears to have fixed the random dropouts during scrobbling. Thanks!
