### ISSUE TITLE
Lost ability to create filters?

### ISSUE THREAD

**Issue by lorefield** [kawaiiDango/pano-scrobbler#517]
Some months ago I bought Pano Scrobbler Supporter on Google Play Store, which should let me write filters for editing. I think I used to have access to that, but now it's only the preset filters. How do I restore access to premium features?

**Comment by kawaiiDango** [comment]
You can add at most 30 regex rules. I think you hit that limit.

**Comment by lorefield** [comment]
Never mind. It was a case of "I've been staring this screen over for 30 minutes, except for the corner the button is in" (It's weird how vision sometimes totally fails to notice something even when you look something over). 

The button is kinda in a weird place when you're in landscape mode: a button on the left-hand sidebar (over avatar and stats) instead of the common bottom-right + icon (where it is in portrait mode).
